# ══════════════════════════════════════════════════════════════
# PRECEDENT CLAUSE LIBRARY — v12.1
#
# Templates use {variable_name} placeholders filled by
# deal_context.get_variable_values() so every proposed
# replacement clause is calibrated to the specific deal.
#
# Variables injected at render time:
#   {liability_cap_months}      e.g. "12", "18", "24"
#   {liability_cap_amount}      e.g. "CAD $250,000"
#   {annual_fees}               e.g. "CAD $120,000"
#   {contract_value}            e.g. "CAD $500,000"
#   {notice_days}               e.g. "30", "60"
#   {cure_period_days}          e.g. "15"
#   {non_compete_months}        e.g. "12"
#   {non_solicitation_months}   e.g. "12"
#   {payment_days}              e.g. "30"
#   {late_fee_pct}              e.g. "1.5"
#   {confidentiality_years}     e.g. "3", "5"
#   {renewal_notice_days}       e.g. "60"
#   {initial_term}              e.g. "one (1) year"
#   {cgl_amount}                e.g. "2,000,000"
#   {eo_amount}                 e.g. "1,000,000"
# ══════════════════════════════════════════════════════════════

PRECEDENT_CLAUSES = {
    "liability_cap": {
        "SaaS / Technology": """Limitation of Liability. Notwithstanding any other provision of this Agreement, the aggregate liability of either party to the other for any and all claims arising under or in connection with this Agreement, whether in contract, tort (including negligence), or otherwise, shall not exceed the total fees paid or payable by the Customer to the Provider in the {liability_cap_months} ({liability_cap_months}) month period immediately preceding the event giving rise to the claim (approximately {liability_cap_amount} based on current annual fees of {annual_fees}). This limitation shall apply even if a party has been advised of the possibility of such damages and even if any limited remedy set out in this Agreement is found to have failed of its essential purpose. For the avoidance of doubt, this clause does not limit liability for: (i) death or personal injury caused by negligence; (ii) fraud or fraudulent misrepresentation; (iii) any liability that cannot be excluded or limited by applicable law.""",

        "Service Agreement": """Limitation of Liability. The total aggregate liability of the Service Provider to the Client under or in connection with this Agreement shall not exceed the total fees paid by the Client to the Service Provider in the {liability_cap_months} ({liability_cap_months}) months preceding the date on which the claim arose (approximately {liability_cap_amount} based on {annual_fees} in annual fees). Neither party shall be liable to the other for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, loss of revenue, loss of data, or loss of goodwill, howsoever caused, whether arising in contract, tort, or otherwise, even if advised of the possibility of such damages.""",

        "Independent Contractor": """Limitation of Liability. The Contractor's total liability to the Client arising out of or in connection with this Agreement shall not exceed the total fees paid by the Client to the Contractor in the {liability_cap_months} ({liability_cap_months}) month period preceding the event giving rise to the claim. The Client's total liability to the Contractor shall be similarly limited. Neither party excludes liability for death, personal injury caused by negligence, or fraud.""",

        "Construction Contract": """Limitation of Liability. The Contractor's aggregate liability to the Owner under this Agreement shall not exceed the greater of: (a) the total contract price of {contract_value}; or (b) the amount recoverable under the Contractor's insurance policies required under this Agreement. This limitation does not apply to: (i) liability for defects in workmanship giving rise to statutory holdback claims under the Construction Act (Ontario); (ii) liability for death or personal injury; or (iii) wilful misconduct or gross negligence. The Construction Act statutory holdback obligations are not modified by this clause.""",

        "Employment Contract": """[Note: Liability limitation clauses in employment contracts are subject to the Employment Standards Act, 2000 (Ontario). Statutory minimums (ESA notice, severance, vacation pay) cannot be limited or waived. Any cap must be above ESA minimums or it is void to that extent. The following applies only to contractual claims above ESA minimums:]\n\nLimitation of Employer Liability. The Employer's liability for wrongful dismissal damages shall not exceed the greater of: (a) the Employee's salary for {liability_cap_months} months; or (b) the minimum entitlements under the Employment Standards Act, 2000, whichever is greater. Nothing in this clause limits the Employee's statutory entitlements under the ESA.""",

        "default": """Limitation of Liability. Neither party's aggregate liability to the other in connection with this Agreement shall exceed the greater of: (a) the total amounts paid or payable under this Agreement in the {liability_cap_months} ({liability_cap_months}) months preceding the claim (approximately {liability_cap_amount}); or (b) CAD $10,000. Neither party shall be liable for indirect, special, incidental, consequential, or punitive damages of any kind, including loss of revenue, loss of profits, or loss of data, regardless of whether such damages were foreseeable.""",
    },

    "indemnity": {
        "SaaS / Technology": """Indemnification. (a) Provider Indemnity: The Provider shall defend, indemnify, and hold harmless the Customer and its officers, directors, employees, and agents ("Customer Indemnitees") from and against any third-party claims, damages, losses, settlements, and reasonable legal fees ("Losses") arising out of or relating to: (i) any allegation that the Provider's platform or software, as provided to the Customer and used in accordance with this Agreement, infringes any Canadian copyright, patent, or trade secret; or (ii) the Provider's breach of its data protection obligations under this Agreement. (b) Customer Indemnity: The Customer shall defend, indemnify, and hold harmless the Provider and its officers, directors, and employees from and against any Losses arising out of: (i) the Customer's use of the platform in violation of this Agreement or applicable law; (ii) Customer Data infringing any third-party intellectual property right; or (iii) the Customer's breach of applicable privacy law. (c) Conditions: The indemnified party shall: (i) promptly notify the indemnifying party in writing of any claim (delay does not waive indemnity unless the indemnifying party is materially prejudiced); (ii) grant the indemnifying party sole control of the defence and settlement (provided the indemnified party may participate at its own cost); and (iii) provide reasonable cooperation at the indemnifying party's expense. The indemnifying party shall not settle any claim that imposes liability or obligation on the indemnified party without prior written consent.""",

        "Service Agreement": """Indemnification. Each party (the "Indemnifying Party") shall indemnify, defend, and hold harmless the other party (the "Indemnified Party") and its officers, directors, employees, and agents from and against any third-party claims, losses, damages, and reasonable legal costs ("Losses") arising from: (a) the Indemnifying Party's material breach of its representations, warranties, or obligations under this Agreement; (b) the Indemnifying Party's negligence or wilful misconduct; or (c) in the case of the Service Provider, any claim that the Services, as delivered and used in accordance with this Agreement, infringe a third party's intellectual property rights in Canada. The Indemnified Party shall give prompt written notice of any claim and shall not settle any claim without the Indemnifying Party's prior written consent, not to be unreasonably withheld or delayed. The Indemnifying Party shall have sole control of the defence, provided the Indemnified Party may participate with counsel of its choosing at its own expense.""",

        "Independent Contractor": """Indemnification. (a) Contractor Indemnity: The Contractor shall indemnify, defend, and hold harmless the Client from and against any third-party claims, losses, and reasonable legal fees arising from: (i) the Contractor's negligence or wilful misconduct in performing the Services; (ii) any claim that the Deliverables, as created and delivered by the Contractor, infringe any Canadian intellectual property right; or (iii) any claim by a third party that the Contractor is an employee of the Client (CRA misclassification claim). (b) Client Indemnity: The Client shall indemnify the Contractor from and against any claims arising from: (i) the Client's misuse of the Deliverables contrary to this Agreement; (ii) claims arising from the Client's instructions that caused the Contractor to infringe a third party's rights; or (iii) the Client's negligence or wilful misconduct.""",

        "default": """Mutual Indemnification. Each party (the "Indemnifying Party") agrees to indemnify, defend, and hold harmless the other party (the "Indemnified Party") and its officers, directors, and employees from and against any third-party claims, losses, damages, and reasonable legal costs arising from: (a) that party's material breach of this Agreement; (b) that party's negligence or wilful misconduct; or (c) that party's violation of applicable law. The indemnified party shall give prompt written notice of any claim and shall cooperate reasonably in the defence at the indemnifying party's cost. Neither party shall settle any claim that imposes liability on the other without prior written consent.""",
    },

    "non_compete": {
        "Independent Contractor": """Non-Solicitation and Restricted Activities. (a) During the term of this Agreement and for a period of {non_compete_months} ({non_compete_months}) months following its termination or expiry for any reason, the Contractor shall not, directly or indirectly, solicit or accept business from any client of the Client with whom the Contractor had material contact during the {non_compete_months} months preceding termination, for the purpose of providing services substantially similar to the Services described in this Agreement. (b) The Contractor acknowledges that: (i) this restriction is reasonable and necessary to protect the Client's legitimate business interests; (ii) it is limited in time and scope; (iii) it does not prevent the Contractor from carrying on their general trade or profession or serving clients with whom the Contractor had no contact; and (iv) courts may reduce but will not eliminate a reasonable non-solicitation clause. [Note: Ontario Bill 27 (Working for Workers Act, 2021) prohibits non-compete clauses for employees but this Agreement is between independent contractors. If this contractor relationship is reclassified as employment, this clause is void to the extent required by s.67.2 of the ESA.]""",

        "Employment Contract": """[MANDATORY NOTICE — ONTARIO: Non-compete provisions are void and unenforceable pursuant to section 67.2 of the Employment Standards Act, 2000 (as amended by the Working for Workers Act, 2021, S.O. 2021, c. 34), except in the context of a sale of a business where the employee is also a vendor of that business. THIS CLAUSE MUST NOT BE USED FOR EMPLOYEES IN ONTARIO. Non-solicitation of clients is a permissible alternative:]\n\nNon-Solicitation of Clients. During the Employee's employment and for a period of {non_solicitation_months} ({non_solicitation_months}) months following the termination of employment for any reason, the Employee shall not, directly or indirectly, solicit or assist any person to solicit any customer or client of the Employer with whom the Employee had material business dealings during the final {non_solicitation_months} months of employment, for the purpose of providing products or services that compete with those of the Employer. This clause does not prevent the Employee from accepting unsolicited business from former clients.\n\nNon-Solicitation of Employees. During the Employee's employment and for {non_solicitation_months} months following termination, the Employee shall not solicit, encourage, or assist any employee of the Employer to leave their employment.""",

        "Franchise Agreement": """Post-Term Non-Compete. (a) During the term of this Agreement and for a period of {non_compete_months} ({non_compete_months}) months following its termination or expiry, the Franchisee shall not, within the Territory defined in Schedule A, directly or indirectly: (i) own, operate, or be employed by any business that competes directly with the Franchise System; or (ii) solicit customers of the Franchise System. (b) The Franchisee acknowledges that the Franchisor has disclosed the proprietary information, System, and trade secrets that justify this restriction, and that the duration and geographic scope are reasonable for franchise agreements under Canadian common law and, where applicable, the Arthur Wishart Act (Franchise Disclosure), 2000 (Ontario).""",

        "default": """Non-Solicitation. During the term of this Agreement and for {non_compete_months} ({non_compete_months}) months following its termination for any reason, each party agrees not to directly solicit for employment or engagement any employee or key contractor of the other party with whom that party had material contact in connection with this Agreement, without the prior written consent of the other party. This clause does not prohibit general advertising not specifically targeted at such individuals.""",
    },

    "ip_ownership": {
        "Independent Contractor": """Intellectual Property Assignment. (a) Assignment of Foreground IP: Subject to clause (b), the Contractor hereby irrevocably assigns to the Client, effective upon creation and conditional upon receipt of full payment, all right, title, and interest in and to all work product, deliverables, inventions, and materials created or developed by the Contractor specifically for the Client under this Agreement ("Foreground IP"), including all copyright, patent rights, trade secrets, and other intellectual property rights therein in all jurisdictions. The Contractor waives all moral rights (as defined under the Copyright Act, R.S.C. 1985, c. C-42) in the Foreground IP to the fullest extent permitted by Canadian law. (b) Contractor Background IP: The Contractor retains all right, title, and interest in and to all tools, methodologies, frameworks, libraries, know-how, and pre-existing materials owned or developed by the Contractor prior to or independently of this Agreement ("Background IP"), a list of which is set out in Schedule B. The Contractor grants the Client a non-exclusive, royalty-free, perpetual, irrevocable licence to use the Background IP to the extent incorporated in the Foreground IP and necessary for the Client's ordinary use of the Foreground IP. (c) Moral Rights Waiver: The Contractor irrevocably waives, in favour of the Client and its successors and assigns, all moral rights in the Foreground IP. [CRITICAL: Canada has no work-for-hire doctrine. IP must be explicitly assigned in writing or it remains with the creator. This clause is essential for independent contractor engagements.]""",

        "SaaS / Technology": """Intellectual Property. (a) Provider Platform IP: As between the parties, the Provider retains all right, title, and interest in and to the platform, software, algorithms, APIs, documentation, and all enhancements, modifications, and derivatives thereof ("Platform IP"). Nothing in this Agreement transfers any Platform IP to the Customer, and the Customer's rights are limited to the licence granted herein. (b) Customer Data: As between the parties, the Customer retains all right, title, and interest in and to all data, content, and materials uploaded, inputted, or generated by the Customer ("Customer Data"). The Provider is granted a limited, non-exclusive, non-transferable licence to use Customer Data solely to provide the Services to the Customer during the term. The Provider shall not use Customer Data to train AI models, conduct analytics for third parties, or for any purpose other than providing the Services. (c) Custom Development: Any features or modules developed specifically for the Customer pursuant to a Statement of Work shall be owned by the Customer upon full payment, subject to the Provider retaining a non-exclusive licence to use the underlying methodology, frameworks, and generalized technical learnings (excluding Customer-specific data and business logic) for other clients. The Provider waives all moral rights in custom deliverables. (d) Feedback: Any feedback, suggestions, or improvement requests provided by the Customer may be used by the Provider without restriction or compensation, provided the Provider does not identify the Customer as the source.""",

        "default": """Intellectual Property. (a) All intellectual property rights in materials created specifically for and at the direction of the Client under this Agreement ("Deliverables") shall be assigned to the Client upon creation and upon full payment of all applicable fees. The assigning party waives all moral rights in the Deliverables to the fullest extent permitted by the Copyright Act (Canada). (b) Each party retains all rights in its pre-existing intellectual property ("Background IP"). Any Background IP incorporated into the Deliverables shall be licensed to the Client on a non-exclusive, royalty-free, perpetual basis solely for the purpose of using the Deliverables as intended. (c) No transfer of Background IP is intended or implied. [Note: Canada has no work-for-hire doctrine — explicit written assignment is required.]""",
    },

    "termination": {
        "SaaS / Technology": """Termination. (a) Termination for Convenience: Either party may terminate this Agreement upon {notice_days} ({notice_days}) days' prior written notice to the other party. (b) Termination for Cause: Either party may terminate this Agreement immediately upon written notice if the other party: (i) commits a material breach that is not remedied within {cure_period_days} ({cure_period_days}) days of written notice specifying the breach in reasonable detail; (ii) becomes insolvent, makes a general assignment for the benefit of creditors, or is the subject of bankruptcy, receivership, or similar proceedings under the Bankruptcy and Insolvency Act (Canada); (iii) in the case of the Provider, experiences a service availability failure exceeding the SLA thresholds for {cure_period_days} or more consecutive calendar days. (c) Effect of Termination: Upon termination for any reason: (i) all licences granted hereunder shall immediately terminate; (ii) the Customer shall pay all fees accrued to the termination date within thirty (30) days; (iii) the Provider shall, within thirty (30) days of written request, provide the Customer with a complete, machine-readable export of all Customer Data at no additional charge; (iv) the Provider shall securely delete all Customer Data within sixty (60) days of the export date, upon written request, and provide written confirmation of deletion. (d) Survival: Sections relating to payment, intellectual property, confidentiality, limitation of liability, indemnity, and dispute resolution survive termination.""",

        "Service Agreement": """Termination. (a) For Convenience: Either party may terminate this Agreement on {notice_days} ({notice_days}) days' written notice without cause. (b) For Cause: Either party may terminate immediately on written notice if the other party is in material breach and such breach remains unremedied within {cure_period_days} ({cure_period_days}) days of written notice particularising the breach. (c) Upon termination for any reason: (i) the Client shall pay all fees earned by the Service Provider up to the termination date, including work in progress on a pro-rata time-and-materials basis; (ii) each party shall return or, at the disclosing party's election, destroy the other's confidential information; (iii) the Service Provider shall deliver all completed work product and all work in progress to the Client. (d) Survival: Payment obligations, intellectual property, confidentiality, limitation of liability, indemnity, and dispute resolution survive termination.""",

        "Employment Contract": """Termination. (a) Termination Without Cause: The Employer may terminate the Employee's employment without cause by providing the Employee with the greater of: (i) the minimum notice or pay in lieu of notice required under the Employment Standards Act, 2000 (Ontario), as may be amended; or (ii) {liability_cap_months} months' written notice or pay in lieu thereof. The parties acknowledge that this provision, if it provides more than the ESA minimum, constitutes a valid agreement to limit common law notice, provided it always meets or exceeds ESA minimums. [Note: ESA minimums cannot be waived. Courts will void caps that fall below ESA minimums. Set {liability_cap_months} generously.] (b) Termination for Cause: The Employer may terminate the Employee's employment for cause as defined under the Employment Standards Act, 2000 and applicable common law, without notice or pay in lieu. (c) Resignation: The Employee shall provide {notice_days} ({notice_days}) days' written notice of resignation.""",

        "Construction Contract": """Termination. (a) Owner's Right to Terminate for Convenience: The Owner may terminate this Contract for convenience upon {notice_days} ({notice_days}) days' written notice to the Contractor. Upon termination for convenience, the Owner shall pay the Contractor for: (i) all work properly performed and materials incorporated up to the termination date; (ii) reasonable demobilisation costs; and (iii) a termination fee equal to [X]% of the unearned contract price, not to exceed CAD ${contract_value}. (b) Termination for Default: Either party may terminate for cause upon {cure_period_days} ({cure_period_days}) days' written notice if the other party is in material default and fails to remedy the default within such period. (c) Construction Act: This Agreement is subject to the prompt payment and adjudication provisions of the Construction Act (Ontario), R.S.O. 1990, c. C.30, as amended. Termination does not extinguish any lien rights under the Construction Act.""",

        "default": """Termination. (a) Either party may terminate this Agreement on {notice_days} ({notice_days}) days' written notice. (b) Either party may terminate immediately if the other party commits a material breach not remedied within {cure_period_days} ({cure_period_days}) days of written notice. (c) On termination, each party shall promptly return the other's confidential information and property, and pay all amounts accrued to the termination date. (d) The following provisions survive termination: payment obligations, intellectual property, confidentiality, limitation of liability, indemnity, and dispute resolution.""",
    },

    "governing_law": {
        "Ontario": """Governing Law and Jurisdiction. This Agreement shall be governed by and construed in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein, without reference to its conflict of laws principles. Each party irrevocably submits to the exclusive jurisdiction of the courts of the Province of Ontario sitting in the City of Toronto for any dispute arising under or in connection with this Agreement, and waives any objection to the exercise of such jurisdiction on the grounds of venue, inconvenient forum, or otherwise. [Note: If the contract specifies a foreign governing law (especially United States), this is a significant risk factor. Mandatory arbitration clauses in foreign jurisdictions substantially disadvantage the Canadian party.]""",
        "British Columbia": """Governing Law. This Agreement is governed by the laws of the Province of British Columbia and the laws of Canada applicable therein. The parties irrevocably submit to the exclusive jurisdiction of the courts of British Columbia sitting in Vancouver.""",
        "Quebec": """Droit applicable / Governing Law. Le présent contrat est régi par les lois de la Province de Québec, y compris le Code civil du Québec, et les lois fédérales du Canada qui s'y appliquent. Les parties se soumettent à la juridiction exclusive des tribunaux du Québec siégeant à Montréal. / This Agreement is governed by the laws of the Province of Quebec, including the Civil Code of Quebec, and the applicable federal laws of Canada. The parties submit to the exclusive jurisdiction of the courts of Quebec sitting in Montreal. [Note: Quebec is a civil law jurisdiction. CCQ 1375 (good faith), CCQ 1437 (abusive clauses), and CCQ 2089 (non-competes) apply mandatorily and cannot be contracted out.]""",
        "default": """Governing Law. This Agreement is governed by and construed in accordance with the laws of the Province of [SPECIFY PROVINCE] and the federal laws of Canada applicable therein. The parties submit to the exclusive jurisdiction of the courts of [SPECIFY PROVINCE]. [Action required: specify a Canadian province. Foreign governing law in a Canadian commercial transaction is a material risk that should be flagged to the client.]""",
    },

    "force_majeure": {
        "default": """Force Majeure. (a) Neither party shall be liable for any delay or failure to perform its obligations under this Agreement (other than payment obligations) to the extent that such delay or failure is caused by a Force Majeure Event. A "Force Majeure Event" means any event beyond a party's reasonable control, including: acts of God; natural disasters (earthquake, flood, hurricane, ice storm); epidemic or pandemic and any associated government actions; acts or omissions of government or regulatory authority (including changes in law); war, armed conflict, terrorism, or civil disturbance; fire or explosion; failure of third-party utility or telecommunications infrastructure; or labour disputes not involving that party's own workforce. (b) Obligations: The party affected shall: (i) give written notice to the other party as soon as reasonably practicable, describing the event, its expected duration, and the affected obligations; (ii) use commercially reasonable efforts to mitigate the effects and resume performance; and (iii) provide written notice when normal performance resumes. (c) Prolonged Force Majeure: If a Force Majeure Event continues for more than sixty (60) consecutive days, either party may terminate this Agreement on {notice_days} days' written notice without liability, except for payment of fees accrued before the Force Majeure Event. Payment obligations are not excused by Force Majeure.""",
    },

    "confidentiality": {
        "default": """Confidentiality. (a) Definition: "Confidential Information" means all non-public information disclosed by one party (the "Disclosing Party") to the other (the "Receiving Party"), whether in written, oral, electronic, or visual form, that is designated as confidential or that reasonably should be understood to be confidential given its nature and the circumstances of disclosure, including business plans, financial information, customer lists, technical specifications, software, pricing, and the terms of this Agreement. (b) Obligations: The Receiving Party shall: (i) hold the Confidential Information in strict confidence using at least the same degree of care it uses to protect its own confidential information, but not less than reasonable care; (ii) use the Confidential Information solely for the purposes of this Agreement; and (iii) not disclose the Confidential Information to any third party without the Disclosing Party's prior written consent, except to employees, officers, contractors, or professional advisors who need to know and are bound by obligations of confidentiality no less protective than those herein. (c) Exceptions: The obligations in clause (b) do not apply to information that: (i) is or becomes publicly available through no fault of the Receiving Party; (ii) was rightfully known to the Receiving Party before disclosure, as evidenced by written records; (iii) is independently developed by the Receiving Party without reference to the Confidential Information; or (iv) is required to be disclosed by law, court order, or regulatory authority, provided the Receiving Party gives prompt written notice to the Disclosing Party before disclosure and reasonably cooperates to seek a protective order. (d) Term: These obligations apply for {confidentiality_years} ({confidentiality_years}) years following termination of this Agreement, except for Trade Secrets, for which the obligations continue for as long as the information qualifies as a trade secret under applicable law. (e) Return/Destruction: Upon termination or written request, the Receiving Party shall promptly return or, at the Disclosing Party's election, certifiably destroy all Confidential Information and all copies thereof.""",
    },

    "dispute_resolution": {
        "default": """Dispute Resolution. (a) Negotiation: If a dispute arises out of or in connection with this Agreement, including any question of its existence, validity, or termination, the parties shall first attempt to resolve it through good faith negotiations between senior representatives of each party. Either party may initiate this process by written notice to the other. If the dispute is not resolved within thirty (30) days of such notice (or such longer period as the parties may agree), either party may refer the matter to mediation under clause (b). (b) Mediation: Before commencing litigation or arbitration, the parties shall attempt non-binding mediation with a mediator agreed upon by the parties. If the parties cannot agree on a mediator within fifteen (15) days, either party may request appointment of a mediator by the ADR Institute of Canada. Mediation costs shall be shared equally. If mediation does not resolve the dispute within sixty (60) days of the mediator's appointment, either party may pursue its remedies under clause (c). (c) Litigation: If the dispute is not resolved through negotiation or mediation, either party may commence proceedings in the courts of competent jurisdiction in accordance with the Governing Law clause. [Note: Mandatory binding arbitration in a foreign jurisdiction is a significant risk factor for the Canadian party. If the counterparty proposes mandatory US arbitration, this should be flagged as a walk-away point.] (d) Interim Relief: Nothing in this clause prevents either party from seeking urgent injunctive or other equitable relief from a court of competent jurisdiction where necessary to prevent irreparable harm, including to protect confidential information or intellectual property.""",
    },

    "payment_terms": {
        "default": """Payment Terms. (a) Invoicing: The Service Provider shall issue invoices in accordance with the fee schedule set out in Schedule A. (b) Payment: Invoices are due and payable within {payment_days} ({payment_days}) days of the invoice date (the "Due Date"). (c) Late Payment: Amounts not paid by the Due Date shall bear interest at the rate of {late_fee_pct}% per month ({late_fee_pct_x12}% per annum), calculated daily and compounded monthly, from the Due Date until the date of actual payment. [Note: Bill C-46 amended s.347.1 of the Criminal Code (Canada), effective January 1, 2025, to cap interest for commercial lending at 35% per annum. The original s.347 threshold of 60% APR also remains in force for other credit arrangements. A late fee of {late_fee_pct}% per month = {late_fee_pct_x12}% APR. Confirm this does not exceed 35% APR for commercial lending. Any clause above 35% APR should be flagged as CRITICAL.] (d) Disputed Invoices: The Client shall pay any undisputed portion of an invoice by the Due Date. Any disputed portion shall be identified by written notice within {payment_days} days of the invoice date, specifying the amount in dispute and the basis. The parties shall resolve invoice disputes through the Dispute Resolution clause. (e) Taxes: All fees are exclusive of applicable taxes, including HST/GST. The Client shall pay all applicable taxes in addition to the fees set out in Schedule A.""",

        "Construction Contract": """Payment Terms — Ontario Construction Act. (a) Progress Payment Applications: The Contractor shall submit monthly progress payment applications to the Owner on the [first] business day of each month. (b) Proper Invoice: Each progress payment application shall constitute a "proper invoice" as defined under section 6.4 of the Construction Act (Ontario). (c) Prompt Payment: The Owner shall pay each proper invoice within twenty-eight (28) days of receipt, as required by the Construction Act. The Contractor shall pay each subcontractor within seven (7) days of receiving payment from the Owner for work performed by that subcontractor. (d) Statutory Holdback: The Owner shall retain a statutory holdback of ten percent (10%) of the value of each progress payment, as required by Part IV of the Construction Act. The holdback shall be released no earlier than forty-five (45) days after the date of publication of a Certificate of Substantial Performance in the Daily Commercial News, or as otherwise required by the Construction Act. (e) Late Payment Interest: Interest on overdue amounts shall be calculated at the rate prescribed under the Construction Act (Ontario). (f) Adjudication: Payment disputes may be referred to adjudication under Part II.1 of the Construction Act without waiving any other remedy.""",
    },

    "auto_renewal": {
        "default": """Term and Renewal. (a) Initial Term: This Agreement commences on the Effective Date and continues for an initial term of {initial_term} (the "Initial Term"), unless earlier terminated in accordance with its terms. (b) Automatic Renewal: At the expiry of the Initial Term, and at the expiry of each Renewal Term, this Agreement shall automatically renew for a further period of {initial_term} (each a "Renewal Term") unless either party provides written notice of non-renewal to the other party at least {renewal_notice_days} ({renewal_notice_days}) days before the expiry of the then-current term. (c) Fee Adjustments on Renewal: The Provider may adjust fees for any Renewal Term by providing written notice of the new fees at least ninety (90) days before the start of that Renewal Term. If the Customer does not provide a non-renewal notice within thirty (30) days of receiving the fee notice, the Customer is deemed to have accepted the adjusted fees. (d) No Tacit Renewal in Quebec: For agreements governed by Quebec law, this clause does not create a tacit renewal (reconduction tacite) beyond the scope permitted by the Civil Code of Quebec.""",
    },

    "data_protection": {
        "default": """Data Protection and Privacy. (a) Compliance: Each party shall comply with all applicable Canadian privacy laws, including the Personal Information Protection and Electronic Documents Act (Canada) ("PIPEDA"), applicable provincial privacy legislation (including Law 25 in Quebec, PIPA in British Columbia and Alberta), and any sector-specific privacy requirements. (b) Collection and Use: Each party shall collect, use, and disclose personal information only: (i) for the purposes identified in this Agreement or as otherwise permitted by applicable law; (ii) with the knowledge and, where required, consent of the individual; and (iii) to the extent reasonably necessary for the identified purpose. (c) Security Safeguards: Each party shall implement and maintain administrative, technical, and physical safeguards appropriate to the sensitivity of the personal information, including: (i) access controls limiting access to authorised personnel; (ii) encryption of personal information in transit and at rest; (iii) regular security assessments; and (iv) a documented incident response procedure. (d) Data Breach Notification: If either party becomes aware of a breach of security involving personal information that creates a real risk of significant harm to any individual, that party shall: (i) notify the other party within seventy-two (72) hours; (ii) notify affected individuals and the Office of the Privacy Commissioner of Canada (or applicable provincial authority) as required by applicable law; and (iii) cooperate fully in investigating and remediating the breach. (e) Sub-Processors: If either party engages a sub-processor to process personal information on its behalf, it shall: (i) obtain prior written consent of the other party; (ii) ensure the sub-processor is bound by data protection obligations no less stringent than those in this Agreement; and (iii) remain fully liable for the sub-processor's compliance. (f) Cross-Border Transfers: Personal information shall not be transferred outside Canada without the prior written consent of the other party and compliance with applicable law (including PIPEDA's accountability principle for international transfers).""",
    },

    "insurance": {
        "default": """Insurance. During the term of this Agreement and for two (2) years thereafter, the Service Provider shall maintain, at its own expense: (a) Commercial General Liability insurance with limits of not less than CAD ${cgl_amount} per occurrence and in the aggregate; (b) Professional Liability (Errors and Omissions) insurance with limits of not less than CAD ${eo_amount} per claim and in the aggregate, covering claims arising from professional services rendered under this Agreement; (c) Workers' Compensation insurance as required by applicable provincial law. The Service Provider shall, upon request, provide the Client with certificates of insurance evidencing the above coverage and naming the Client as an additional insured on the CGL policy. The Service Provider shall give at least thirty (30) days' prior written notice of any material change or cancellation of such insurance. [Note: Absence of insurance requirements in a service agreement transfers risk to the Client. CGL of CAD ${cgl_amount} and E&O of CAD ${eo_amount} reflect the deal size and industry risk tier for this engagement.]""",

        "Construction Contract": """Insurance — Construction. The Contractor shall maintain, at its own expense throughout the performance of the Work and for a period of two (2) years following Substantial Performance: (a) Commercial General Liability: Not less than CAD $5,000,000 per occurrence and in the annual aggregate, including products and completed operations coverage, and broad form property damage. The Owner shall be named as additional insured. (b) Professional Liability (Design-Build): Not less than CAD $2,000,000 per claim if the Contractor is providing design services. (c) Builder's Risk / Installation Floater: Covering the full replacement value of the Work during construction, as agreed between the parties. (d) Workers' Compensation: As required by the Workplace Safety and Insurance Act (Ontario) or applicable provincial legislation. (e) Automobile Liability: Not less than CAD $2,000,000. (f) Umbrella/Excess Liability: Not less than CAD $5,000,000 in excess of the primary coverages above. All policies shall be with insurers licensed in Canada with an AM Best rating of A- or better. The Contractor shall provide certificates of insurance and, where required, copies of policy endorsements, prior to commencement of the Work. [Note: Construction projects require specialized coverage. CCIP/OCIP wrap-up programmes may apply on large projects.]""",
    },
}


def get_precedent(clause_category: str, contract_type: str) -> str:
    """Return the raw (unrendered) precedent template for a category and contract type."""
    category = PRECEDENT_CLAUSES.get(clause_category, {})
    return (category.get(contract_type)
            or category.get("default")
            or "")


def render_precedent(clause_category: str, contract_type: str, variables: dict) -> str:
    """
    Return the precedent clause with all {variable_name} placeholders filled
    from the provided variables dict (from deal_context.get_variable_values()).
    Falls back gracefully if a variable is missing.
    """
    template = get_precedent(clause_category, contract_type)
    if not template:
        return ""
    # Add computed variables
    extended = dict(variables)
    try:
        late_fee = float(variables.get("late_fee_pct", "1.5"))
        extended["late_fee_pct_x12"] = f"{late_fee * 12:.1f}"
    except (ValueError, TypeError):
        extended["late_fee_pct_x12"] = "18.0"
    # Fill placeholders, leave unfilled ones as-is for transparency
    import re
    def replacer(m):
        key = m.group(1)
        return extended.get(key, m.group(0))  # keep original if not found
    return re.sub(r'\{(\w+)\}', replacer, template)


def _truncate_at_sentence(text: str, max_chars: int = 800) -> str:
    """Truncate at a sentence boundary rather than mid-word or mid-clause.

    A hard character cut at 700 chars can produce legally misleading text by
    cutting mid-sentence (e.g. "liability shall not exceed..." with the cap
    amount on the next line). This function finds the last complete sentence
    within the limit before truncating.
    """
    if len(text) <= max_chars:
        return text
    window = text[:max_chars]
    # Look for the last sentence-ending punctuation followed by whitespace
    for delimiter in ('. ', '.\n', '; ', ';\n', ') ', ')\n'):
        idx = window.rfind(delimiter)
        if idx > max_chars * 0.5:  # Only accept if we keep at least half
            return window[:idx + len(delimiter)].rstrip() + " [...]"
    # Fallback: break at last space to avoid mid-word cut
    idx = window.rfind(' ')
    return (window[:idx] if idx > 0 else window) + " [...]"


def format_precedents_for_prompt(contract_type: str, variables: dict = None) -> str:
    """
    Format all relevant precedent clauses for injection into the system prompt.
    If variables are provided, renders templates; otherwise shows raw templates.
    """
    lines = [
        "The following vetted Canadian precedent clauses are available.",
        "Where you propose a replacement clause, ADAPT the most relevant precedent below",
        "rather than drafting from scratch. Fill in any remaining [bracketed] values",
        "from the contract context or deal context provided.\n"
    ]
    for cat_key, variants in PRECEDENT_CLAUSES.items():
        raw = variants.get(contract_type) or variants.get("default") or ""
        if not raw:
            continue
        label = cat_key.replace("_", " ").title()
        if variables:
            rendered = render_precedent(cat_key, contract_type, variables)
            clause_text = rendered
        else:
            clause_text = raw
        # Truncate for prompt — show enough to be useful
        truncated = _truncate_at_sentence(clause_text, max_chars=800)
        lines.append(f"--- {label} ---")
        lines.append(truncated)
        lines.append("")
    return "\n".join(lines)
